const version = process.env.REACT_APP_API_VERSION

const EndPoint = {
  LOGIN_API: `/auth/login`,
  DPA_ACCEPT : `/${version}/dpa/accept`,
  SEND_QUERY : `/${version}/chatbot/query`,
  CHATBOT_FILE_UPLOAD:`/${version}/user/claim-tickets/temp-upload`,
  NATIONAL_ID_VERIFICATION_STATUS : `/validate-identificacion`,
  NATIONAL_ID_VERIFICATION: `/person-info`,
  INDIVIDUAL_PERSON_VALIDATE : `/validate-individual-person`,
  SEND_OTP : `/register/request-otp`,
  VERIFY_OTP:`/register/verify-otp`,
  REGISTER_API:'/register',
  ACCOUNT_API : `/${version}/account`,  
  DOWNLOAD_PROFILE_PICTURE : `/${version}/account/download-profile-picture`,
  SEND_LOGIN_OTP : '/send-login-otp',
  VERIFY_LOGIN_OTP : '/verify-login-otp',
  RESEND_LOGIN_OTP : '/resend-login-otp',
  MASTER_DATA_API : `/${version}/masters`,
  MASTER_INQUIRY_TYPE_LIST : `/${version}/masters/inquiry-type-list`,
  MASTER_INQUIRY_SUB_TYPE_LIST : `/${version}/masters/inquiry-sub-type-list`,
  MASTER_CLAIM_TYPE_LIST : `/${version}/masters/claim-type-list`,
  MASTER_CLAIM_SUB_TYPE_LIST : `/${version}/masters/claim-sub-type-list`,
  MASTER_ORGANIZATIONAL_UNIT : `/${version}/masters/organization-list`,
  MASTER_PROVINCE_LIST :  `/${version}/masters/province-list`,
  MASTER_CITY_LIST :  `/${version}/masters/city-list`,
  FILE_CLAIM_SUBMIT : `/${version}/user/claim-tickets/file-claim`,
  LIST_CLAIMS : `/${version}/user/claim-tickets`,
  CLAIM_TICKETS : `/${version}/user/claim-tickets`,
  CLAIM_STATS:`/${version}/user/claim-tickets/count-by-status`,
  FILE_CLAIM_SECOND_INSTANCE: `/${version}/user/claim-tickets/file-second-instance-claim`,
  DOWNLOAD_DOCUMENT: `/${version}/user/claim-tickets/download`,
  DOWNLOAD_TICKET_DETAILS: `/${version}/user/claim-tickets`,
  TICKET_CHAT:`/${version}/user/claim-tickets`,
  FILE_COMPLAINT: `/${version}/user/claim-tickets/file-complaint`,
  TICKET_DETAIL_DOWNLOAD_PDF :`/${version}/user/claim-tickets`,
  NOTIFICATION_LIST : `/${version}/notifications`,
  READ_SINGLE_NOTIFICATION : `/${version}/notifications`,
  READ_ALL_NOTIFICATIONS : `/${version}/notifications/mark-as-read-all`,
  DELETE_SINGLE_NOTIFICATION : `/${version}/notifications`,
  DELETE_ALL_NOTIFICATIONS : `/${version}/notifications/delete/all`,
  NOTIFICATION_COUNT : `/${version}/notifications/count`,
};

export default EndPoint;
